### ISSUE TITLE
Output of app is broken after gulp bundle

### ISSUE THREAD

**Issue by MarijnMensinga** [matoilic/generator-angular-lazy#16]
Hi,

After installing a fresh new version of `angular-lazy` and and running `gulp build` the output (via localhost:8088) of the webapp is 'index-state'. This is totally fine. 

Then I run `gulp bundle`. Now when I open the app (via localhost:8088) it outputs `[object Object]` and it does not have any js errors. Am I doing something wrong or is there a bug somewhere in the `gulp bundle` process?

Also I was wondering if it would be possible to run `gulp dist` which creates a folder `dist` which can be copied 1-on-1 to a production environment where it can be used. So reverting changes in `system.js` to continue development isn't necessary.

I look forward to hearing from you.
Marijn

**Comment by MarijnMensinga** [comment]
After some further investigation it seems to go wrong during the loading of templates:

Main.js:2550 _(line number is an approximation)_

``` javascript
var _application = $__require('./application.html!text');
var _application2 = _interopRequireDefault(_application);
  function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {default: obj};
  }

function applicationRouteConfig($stateProvider) {
    $stateProvider.state('app', {
      url: '/',
      abstract: true,
      views: {page: {
          controller: 'ApplicationController as application',
          template: _application2.default
        }}
    });
  }
```

Here we expect `_application2.default` to be a string, but it is an object: `ModuleRecord { default="  ..here be html.. "}`.
The problem seems to be that the `_interopRequireDefault` function expects the result to have a `__esModule` flag when it is es6 transpiled. Since the flag isn't set on `_application` but does contain a `default` parameter, it gets double wrapped resulting in `{default: ModuleRecord{default: " ..here be html.. "}}`

So I'm wondering what the origin of this problem is. Is it the babel transpiler? The JSPM loader?_(Which works fine on the non-bundled version)_ The bundler? Or is it something else..?

I'm really looking forward to hearing from you.
Marijn

**Comment by photusenigma** [comment]
+1

**Comment by bdurrer** [comment]
I like your idea for an default dist "export" task. I created my own task for a maven build: [maven.task.js.txt](https://github.com/matoilic/generator-angular-lazy/files/346260/maven.task.js.txt)

**Comment by matoilic** [comment]
For some reason the code got transpiled twice. I've disabled the transpilation within SystemJS since it's not really needed and caused this issue.

@bdurrer For packaging JS into a WAR or JAR I would suggest using maven-resources-plugin or maven-war-plugin. Gulp should only be responsible for building the JavaScript app and Java specific stuff should then be handled by Maven. But that's just a preference of mine :), not necessarily a best practise.

**Comment by bdurrer** [comment]
@matoilic aye, the maven part was actually a bit misleading, this can of course be achieved by the maven plugins themself.
The idea of the task is to bundle everything needed for running it in an output directory for further processing. I think the project should know how to bundle itself, instead of secondary process being required to filter out the irrelevant parts (like the 160MB node_modules).
