### ISSUE TITLE
Production browser bootstrap

### ISSUE THREAD

**Issue by oktango** [matoilic/generator-angular-lazy#2]
It is not clear how to run the minified production version of the application in the browser.

**Comment by matoilic** [comment]
Just realized that this is missing from the documentation. In production you'd run `gulp bundle` as a last build step. You can find more information on the bundler [here](https://github.com/matoilic/angular-lazy-bundler). I'll adapt the docs soon.

**Comment by oktango** [comment]
gulp bundle produces two js files: index.js and main.js. It is not clear how to put it in the html file.

**Comment by matoilic** [comment]
You don't need to change anything. The bundle task takes care of everything. I've updated [the documentaiton](https://github.com/matoilic/generator-angular-lazy#preparing-for-production) to clarify the process. Let me know if something is still unclear.

**Comment by oktango** [comment]
So, there are no separated browser production version?
It seems like the code must be running on node.js even in production?

**Comment by matoilic** [comment]
Node is not required in production. Both, in development and production, [SystemJS](https://github.com/systemjs/systemjs) takes care of loading the app resources and it runs on its own in the browser. In production you use a different configuration for it – generated by the `bundle` task – so that it loads the bundles instead of the individual files. There is an example project [here](https://github.com/matoilic/angular-lazy-workshop) where you can play around with it.

**Comment by oktango** [comment]
Thanks for explanation. An example project you provided works fine for me.
I believe some files are missing in current system.js config in 'bundles' section. When I run application in browser it tries to load non-existing files like
/jspm_packages/npm/babel-core@5.8.35/external-helpers.js
/jspm_packages/github/matoilic/angular-lazy@0.2.1.js

**Comment by borntorun** [comment]
Hi
I'm new to jspm and I'm trying to understand how to deploy an app created with generator-angular-lazy  to production (using heroku). 
My question is: 
- after build + bundle what exactly must me deployed? the build dir + the config dir ? 
  and what about jspm_packages dir, must it be deployed too or everything is on the bundle?

**Comment by matoilic** [comment]
After bundling you would need to deploy 
- build/bundles
- config/system.js
- jspm_packages/system.src.js

You cold also use jspm_packages/system.js instead of jspm_packages/system.src.js since it's the compressed version of SystemJS. If you link to images, fonts or other assets within your stylesheets then you would also need to deploy those from build/components or wherever you've put them.

**Comment by borntorun** [comment]
Thanks for your fast response.

I reached the @oktango mentioned issue: Error: XHR error (404 Not Found) loading http://.../jspm_packages/npm/babel-core@5.8.35/external-helpers.js

My dist struct is like this:
- index.html
- bundles/
  - (... everything created by gulp bundle)
- config/
  - system.js
- jspm_packages/
  - system.js

In config/system.js I needed to change paths:
`paths: {
    "*": "*", ...
  }`
removing the reference to the "build" folder.

If I add the jspm_packages/npm/babel.../external-helpers.js it works; my question is: should not the external-helpers being include in the bundles also? If yes, how?

**Comment by matoilic** [comment]
If external-helpers is missing, you can add it to the bundle by adding it to the list of packages to bundle like here: https://github.com/matoilic/angular-lazy-workshop/blob/master/gulpfile.js#L104.

If you keep the folder structure `build/bundles` then you'll not need to change the `paths` option.
